### ISSUE TITLE
issue in integrating in foreman

### ISSUE THREAD

**Issue by nagarjuna** [fog/fog-vsphere#10] opened 2015-11-25 09:42 UTC
I am trying to integrate fog-vsphere gem in foreman(http://www.theforeman.org/) application. When i try to use, i am getting below error

config = {
  provider: 'vsphere',
  vsphere_ssl: true,
  vsphere_rev: '4.0', # also fails using 4.1
  vsphere_username: 'root',
  vsphere_password: 'somepassword',
  vsphere_server: 'vcenter01',
  vsphere_expected_pubkey_hash: 'hash'
}

connection = Fog::Compute.new(config)

TypeError: superclass mismatch for class Vsphere
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/fog-vsphere-0.1.1/lib/fog/vsphere/compute.rb:5:in `<module:Compute>'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/fog-vsphere-0.1.1/lib/fog/vsphere/compute.rb:4:in `<module:Fog>'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/fog-vsphere-0.1.1/lib/fog/vsphere/compute.rb:3:in `<top (required)>'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.32.0/lib/fog/core/services_mixin.rb:28:in `require_service_provider_library'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.32.0/lib/fog/core/services_mixin.rb:14:in `new'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.32.0/lib/fog/compute.rb:62:in `new'
	from (irb):12
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.21/lib/rails/commands/console.rb:47:in `start'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.21/lib/rails/commands/console.rb:8:in `start'
	from /home/nagarjuna/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.21/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'1.9.3-p547 :013 >

**Comment by shlomizadok** [comment] 2015-11-25 11:30
@nagarjuna #11 solves it (see also discussion here: https://github.com/theforeman/foreman/pull/2900#issuecomment-159566435)

**Comment by timogoebel** [comment] 2015-11-25 17:21
@shlomizadok : I tested this more thorough, I think the problem is still there:

The changes I made to my local foreman env:
```
diff --git a/Gemfile b/Gemfile
index 19ceae4..292c0b2 100644
--- a/Gemfile
+++ b/Gemfile
@@ -29,7 +29,7 @@ gem 'i18n', '~> 0.6.4'
 gem 'rails-i18n', '~> 3.0.0'
 gem 'turbolinks', '~> 2.5'
 gem 'logging', '>= 1.8.0', '< 3.0.0'
-gem 'fog-core', '1.34.0'
+gem 'fog-core', '1.35.0'
 gem 'net-scp'
 if RUBY_VERSION.start_with? '1.9.'
   gem 'net-ssh', '< 3'
diff --git a/bundler.d/fog.rb b/bundler.d/fog.rb
index 2e79443..ce1c0d8 100644
--- a/bundler.d/fog.rb
+++ b/bundler.d/fog.rb
@@ -1,3 +1,3 @@
 group :fog do
-  gem 'fog', '1.36.0', :require => false
+  gem 'fog', :path => '/.../foremandev/fog'
 end
diff --git a/bundler.d/vmware.rb b/bundler.d/vmware.rb
index abe76eb..e8f7011 100644
--- a/bundler.d/vmware.rb
+++ b/bundler.d/vmware.rb
@@ -1,3 +1,4 @@
 group :vmware do
   gem "rbvmomi", '~> 1.8'
+  gem 'fog-vsphere', :path => '/../foremandev/fog-vsphere'
 end
```

fog and fog-vsphere are at the latest commit.

This results in the following error:
```
TypeError: superclass mismatch for class Vsphere
```

I think, the changes to fog are also important. If I omit them, everything works - but the new code in fog-vsphere is not available.
Any idea why this is still happening? I believe, it correlates with the fog extensions introduced by foreman. Have to investigate this, though.

**Comment by timogoebel** [comment] 2015-11-26 09:41
This is not a fog issue, it's a foreman one. This is what you need to do:

```
diff --git a/Gemfile b/Gemfile
index 19ceae4..292c0b2 100644
--- a/Gemfile
+++ b/Gemfile
@@ -29,7 +29,7 @@ gem 'i18n', '~> 0.6.4'
 gem 'rails-i18n', '~> 3.0.0'
 gem 'turbolinks', '~> 2.5'
 gem 'logging', '>= 1.8.0', '< 3.0.0'
-gem 'fog-core', '1.34.0'
+gem 'fog-core', '1.35.0'
 gem 'net-scp'
 if RUBY_VERSION.start_with? '1.9.'
   gem 'net-ssh', '< 3'
diff --git a/app/models/concerns/fog_extensions.rb b/app/models/concerns/fog_extensions.rb
index 7fa1430..53a88a1 100644
--- a/app/models/concerns/fog_extensions.rb
+++ b/app/models/concerns/fog_extensions.rb
@@ -53,6 +53,7 @@ end

 if SETTINGS[:vmware]
   require 'fog/vsphere'
+  require 'fog/vsphere/compute'
   require 'fog/vsphere/models/compute/server'
   Fog::Compute::Vsphere::Server.send(:include, FogExtensions::Vsphere::Server)

diff --git a/bundler.d/fog.rb b/bundler.d/fog.rb
index 2e79443..c1976d8 100644
--- a/bundler.d/fog.rb
+++ b/bundler.d/fog.rb
@@ -1,3 +1,3 @@
 group :fog do
-  gem 'fog', '1.36.0', :require => false
+  gem 'fog', :path => '/Users/f0218175/foremandev/fog', :require => false
 end
diff --git a/bundler.d/vmware.rb b/bundler.d/vmware.rb
index abe76eb..e8f7011 100644
--- a/bundler.d/vmware.rb
+++ b/bundler.d/vmware.rb
@@ -1,3 +1,4 @@
 group :vmware do
   gem "rbvmomi", '~> 1.8'
+  gem 'fog-vsphere', :path => '/Users/f0218175/foremandev/fog-vsphere'
 end
```

**Comment by plribeiro3000** [comment] 2015-11-26 11:22
@nagarjuna Can you confirm that what @timogoebel suggested works?

Thanks!

**Comment by timogoebel** [comment] 2016-01-12 13:32
@plribeiro3000 : I think, you can close this issue as foreman now uses fog 1.37.0 and fog-vsphere..

**Comment by plribeiro3000** [comment] 2016-01-12 13:33
Awesome. Thanks!

**Closed by plribeiro3000** 2016-01-12 13:33 UTC
